/*
 * generated by Xtext 2.11.0.RC2
 */
package com.github.jmodel.validator.plugin.ide


/**
 * Use this class to register ide components.
 */
class ValidationLanguageIdeModule extends AbstractValidationLanguageIdeModule {
}
